apiVersion: apps/v1
kind: Deployment
metadata:
  name: mervs-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mervs-demo-app
  template:
    metadata:
      labels:
        app: mervs-demo-app
    spec:
      containers:
- name: app
  image: harbor.vstcloud.io/library/mervs-demo-app:v1
  ports:
  - containerPort: 3000
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
